Repository DIT113-V22/group-15, pull requests merged in 2022-05, with the labels that each got.

#28 Delete duplicate file
  sketch_obstacle_aavoidance.ino
Labels: invalid, Sprint #1

#35 Send movement commands to shopping assistant
  Website/code_not_in_use
  Website/index.js
  Website/script.js
  models/post.js
  package-lock.json
  package.json
  public/Instructions.md
  public/index.js
  server.js
Labels: website, Sprint 2, Sprint#3

#49 Delete style2.css
  Website/style2.css
Labels: duplicate

#58 Update mega linter
  .github/workflows/mega-linter.yml
Labels: bug

#69 Readme update
  README.md
Labels: documentation

#70 CarTalk and login
  LogIn/test.html
  Website/login.css
  Website/login.html
  Website/script.js
Labels: website, Sprint 2

#71 Mqtt Website communication
  Website/HomePage.html
  Website/script.js
  public/Instructions.md
  public/index.html
  public/index.js
  server.js
Labels: Sprint 2, Sprint#3

#72 - #29 Created a new appearance for the login page
  Website/login.css
  Website/login.html
  public/index.html
Labels: Sprint 2, Sprint#3

#73 Cleaned the code
  Website/HomePage.html
  Website/background_IMG.jpg
  Website/bg_img2.jpg
  Website/login.css
  Website/login.html
  Website/script.js
  Website/styleWeb.css
  arduino/smartcar/smartcar.ino
  public/index.html
  public/style.css
Labels: enhancement
